### ISSUE TITLE
Stopped working after jQuery updated to 3.1.1.

### ISSUE THREAD

**Issue by niraj315** [jfeldstein/jQuery.AjaxFileUpload.js#54]
It was working beautifully. before I  update jQuery, Just updating to jQuery version 3.1.1.  it has broken.
when I click for upload it shows error : 
                                  `TypeError: this.context is undefined`
I checked  jQuery.AjaxFileUpload.js is updated in my code.

**Comment by Zholaman** [comment]
Yes, this plugin do not working with jQuery 3.1.1, we are getting this error :
TypeError: $(...).ajaxfileupload is not a function

**Comment by psiegel404** [comment]
This issue can easily be fixed so that it works with jQuery 3.4.1. You just need to edit line 138 in the js file like following:
before:
`$('#'+frame_id).load(function() {`
after:
`$('#'+frame_id).on('load', function() {`

worked for me like a charm
